---
- name: Install Docker, Java, Minikube, and Kubectl on Slave Node
  hosts: slaves
  become: yes  # Run as sudo
  tasks:

    - name: Update APT package index
      apt:
        update_cache: yes

    - name: Install dependencies
      apt:
        name:
          - apt-transport-https
          - ca-certificates
          - curl
          - software-properties-common
          - gnupg
        state: present

    - name: Install Java (default JDK)
      apt:
        name: default-jdk
        state: present

    - name: Install Docker
      shell: |
        curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
        add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
        apt update
        apt install -y docker-ce
      args:
        executable: /bin/bash

    - name: Add user to Docker group
      user:
        name: ubuntu
        groups: docker
        append: yes

    - name: Install Minikube
      shell: |
        curl -LO https://storage.googleapis.com/minikube/releases/latest/minikube-linux-amd64
        install minikube-linux-amd64 /usr/local/bin/minikube
      args:
        executable: /bin/bash

    - name: Install Kubectl
      shell: |
        curl -LO "https://dl.k8s.io/release/$(curl -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
        install kubectl /usr/local/bin/kubectl
      args:
        executable: /bin/bash

    - name: Verify kubectl installation
      shell: kubectl version --client
      register: kubectl_version
      changed_when: false

    - name: Display kubectl version
      debug:
        msg: "{{ kubectl_version.stdout }}"
