apiVersion: v1
kind: Service
metadata:
  name: puzzle-service
  namespace: puzzle-namespace
spec:
  selector:
    app: puzzle
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5173
      nodePort: 30080
  type: LoadBalancer
