apiVersion: v1
kind: Service
metadata:
  name: puzzle-service
  namespace: puzzle-namespace
spec:
  selector:
    app: puzzle
  ports:
    - protocol: TCP
      port: 80        # Port inside the cluster
      targetPort: 5173  # Your application's internal port
      nodePort: 30080  # External port to access the service
  type: NodePort  # Change from LoadBalancer to NodePort
